### ISSUE TITLE
why use slices ?

### ISSUE THREAD

**Issue by LinJM** [johnsmithm/handwritten-tf-1.0#1]
hello, @johnsmithm , I found you use slices to cut the original input image to a pack of slices, why not just use CNN stride param to represent the sliding windows?

And when you use slices, how to handle the labels？ It's hard to align each slice with a correct label.

**Comment by johnsmithm** [comment]
hi,
cnn strike is for the small kernel, i do not think one can manage to configure strikes for cnn such that each new at the end will have a list of slices. a slice has the dimention of the height of the orginal image and width of 30 pixels, with step 3(set with stride). 
ctc is use to assign labels to all slices having just the whole text for original image, it learns to align correct the lebels.
