### ISSUE TITLE
Documentation lack

### ISSUE THREAD

**Issue by ghost** [johnsmithm/handwritten-tf-1.0#3]
Peace be upon you,
@johnsmithm
- What are the required dependencies/prerequisite?

- is there `nhidden` option for training, LSTM units in hidden layer?

- How to train .txt/png pairs?
[example data: Arabic example data.zip](https://github.com/johnsmithm/handwritten-tf-1.0/files/1200340/Arabic.11.lines.zip)

- How to use the trained model to ocr some images?

- Can your software conduct line/layout segmentation & binarization?

**Comment by johnsmithm** [comment]
done
