### ISSUE TITLE
Unable to find tfrecords needed for Training

### ISSUE THREAD

**Issue by selcouthlyBlue** [johnsmithm/handwritten-tf-1.0#4]
I tried to execute the command for training but it is unable to find the tfrecord files needed

`NewRandomAccessFile failed to Create/Open: ../tf-data/handwritten-test-54.tfrecords : The system cannot find the path specified.`

How do I make the tfrecord files needed for training and testing? :O

**Comment by johnsmithm** [comment]
https://github.com/johnsmithm/handwritten-tf-1.0/blob/master/make%20tfRecods.ipynb

**Comment by selcouthlyBlue** [comment]
Thank you so much :D

**Comment by selcouthlyBlue** [comment]
I tried running make tfRecods.ipynb and it gave me this error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-11-99b33549b318> in <module>()
----> 1 makeBatchesTFRecord('batch/tf-data-40x320-81/','../xml/','../forms/',20,True)

<ipython-input-7-e27e4723db6b> in makeBatchesTFRecord(pathSave, pathXML, pathImgs, batchSize, words)
     37                 break
     38 
---> 39             texts,imgs,lengths = processPage(xml,img,words)
     40 
     41 

<ipython-input-3-16936e11aa9b> in processPage(nameXml, nameImg, words, maxW)
     47                     jj=jjj
     48                 if e1-b>maxW and t!="":
---> 49                         img = form[jj:ss,b:e]
     50                         img = cv2.resize(img, (0,0), fx=0.3, fy=0.3)
     51                         ret,thresh1 = cv2.threshold(img,int(line.attrib['threshold']),255,cv2.THRESH_BINARY)

TypeError: 'NoneType' object is not subscriptable
```

**Comment by selcouthlyBlue** [comment]
Alright, I made it work somehow with this commit https://github.com/selcouthlyBlue/handwritten-tf-1.0/commit/f0e1af77d2477c8879b4b2e161e1ec192cb84b69 but all I'm getting now are tfRecords that are empty (0 bytes in size). I didn't get any errors when I ran the ipynb. Have you encountered this error before? How do I fix it? :o
