### ISSUE TITLE
makeTFRecords generates TFRecords with 0 bytes

### ISSUE THREAD

**Issue by selcouthlyBlue** [johnsmithm/handwritten-tf-1.0#5]
I ran makeTFRecords.ipynb to generate the TFRecords needed for training after the modification made to it in this [commit ](https://github.com/selcouthlyBlue/handwritten-tf-1.0/commit/f0e1af77d2477c8879b4b2e161e1ec192cb84b69). But it gives me errors in this line:

`for ii in range(batchSize):
                        if totalI[ii].shape[0] < 50 or totalI[ii].shape[0] > 200 or \
                        totalI[ii].shape[1]<10 or totalI[ii].shape[1]>40:
                            print('error!!')
                            continue`

I downloaded the handwriting images and xmls needed to make the TFRecords from [IAM](http://www.fki.inf.unibe.ch/databases/iam-handwriting-database/download-the-iam-handwriting-database). I'm using Tensoflow 1.2.1 and the OS of my machine is Windows.

**Comment by gangooteli** [comment]
I am also facing the same error. Will look into it and in case if I find any solution, will try to resolve it

**Comment by karthikrajkumar** [comment]
I am also facing the same problem. Any solution for this ?

**Comment by manhcuogntin4** [comment]
Remove lines : for ii in range(batchSize): if totalI[ii].shape[0] < 50 or totalI[ii].shape[0] > 200 or \ totalI[ii].shape[1]<10 or totalI[ii].shape[1]>40: print('error!!') continue. It worked for me. But I don't know it can raise the problem in the training.

**Comment by johnsmithm** [comment]
new update
