### ISSUE TITLE
Not able to tun the program

### ISSUE THREAD

**Issue by sharmaannapurna** [johnsmithm/handwritten-tf-1.0#7]
When I tried running the given commad I got following on the screen...Its not running and repeating the same 
```INFO:tensorflow:/job:master/task:0: Entering training loop.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:separable_lstm/model.ckpt-0 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:separable_lstm/model.ckpt-0 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:global_step/sec: 0
```

**Comment by johnsmithm** [comment]
python train.py --slices 55 --width 12 --stride 1  --Bwidth 350 --vocabulary_size 29 \
--height 25 --train_data_pattern test-batch1/handwritten-test-{}.tfrecords --train_dir models-feds \
--test_data_pattern test-batch1/handwritten-test-{}.tfrecords  --max_steps 20 --batch_size 20 --beam_size 1 \
--input_chanels 1 --start_new_model --rnn_cell LSTM --model LSTMCTCModel --num_epochs 6000

**Comment by johnsmithm** [comment]
open if does not work
